#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Clean the recorded sim bag for use as a runtime-baseline LiDAR source.

The bag was recorded from the Gazebo sim, whose AMCL published map->odom on
/tf. Replaying that fights slam_toolbox (SLAM must own the map frame) and AMCL
(nav phase must own it too). This copies the bag, dropping:
  * any /tf transform whose parent frame is 'map'  (keep odom->base_footprint)
  * /clock  (regenerated by `ros2 bag play --clock`)
Everything else (/scan, /odom, /tf_static) passes through untouched.

Usage: filter_bag.py <in_bag_dir> <out_bag_dir>
"""
import sys

import rclpy.serialization as ser
from rosbag2_py import (
    ConverterOptions, SequentialReader, SequentialWriter, StorageOptions)
from tf2_msgs.msg import TFMessage

DROP_TOPICS = {'/clock'}


def main():
    src, dst = sys.argv[1:3]
    reader = SequentialReader()
    reader.open(StorageOptions(uri=src, storage_id='mcap'),
                ConverterOptions('', ''))
    topics = {t.name: t for t in reader.get_all_topics_and_types()}

    writer = SequentialWriter()
    writer.open(StorageOptions(uri=dst, storage_id='mcap'),
                ConverterOptions('', ''))
    for name, t in topics.items():
        if name in DROP_TOPICS:
            continue
        writer.create_topic(t)   # reuse the source topic metadata (incl. QoS)

    kept = dropped_tf = 0
    while reader.has_next():
        name, data, stamp = reader.read_next()
        if name in DROP_TOPICS:
            continue
        if name == '/tf':
            msg = ser.deserialize_message(data, TFMessage)
            msg.transforms = [tr for tr in msg.transforms
                              if tr.header.frame_id != 'map']
            dropped_tf += 1
            if not msg.transforms:
                continue
            data = ser.serialize_message(msg)
        writer.write(name, data, stamp)
        kept += 1
    print(f'wrote {dst}: kept {kept} msgs, cleaned map->odom from {dropped_tf} '
          f'/tf msgs, dropped {sorted(DROP_TOPICS)}')


if __name__ == '__main__':
    main()
